### ISSUE TITLE
我的设备图标问题

### ISSUE THREAD

**Issue by isoulgh** [CalvinXu17/OpenCore-Dell-G3-3579-1060mq#1]
感谢您的分享，解决了我这段时间一直困惑的问题，
不过我发现在设置-》applid里面mac这个设备的图标显示不出来诶
登录苹果官网的appleid管理，mac的图标也显示不出来，我查找图片的源地址，更改连接里的macbookpro16,2为其他比如说16,1以及其他。发现就macbookpro16,2和16,3的图标无法显示
虽然说不影响正常使用，但感觉很不舒服诶

**Comment by CalvinXu17** [comment]
> 诶

暂未解决该问题，我也是这样，一开始我以为是Apple服务器问题，回头我再看看

**Comment by CalvinXu17** [comment]
> 感谢您的分享，解决了我这段时间一直困惑的问题，
> 不过我发现在设置-》applid里面mac这个设备的图标显示不出来诶
> 登录苹果官网的appleid管理，mac的图标也显示不出来，我查找图片的源地址，更改连接里的macbookpro16,2为其他比如说16,1以及其他。发现就macbookpro16,2和16,3的图标无法显示
> 虽然说不影响正常使用，但感觉很不舒服诶

暂未解决该问题，我也是这样，一开始我以为是Apple服务器问题，回头我再看看

**Comment by isoulgh** [comment]
我解决了这个问题，我测试过降低到15,2可以解决。
貌似在这个网页里https://support.apple.com/en-us/HT201300，机型后面带Four/Two Thunderbolt 3 ports的机型都可以使用c口外接显示器
虽然我并不明白这是为什么。

**Comment by isoulgh** [comment]
https://appleid.cdn-apple.com/static/deviceImages-10.0/MacBookPro/MacBookPro15,2/online-infobox__3x.png
看有没有图标，可以通过这个网址更改MacBookPro15,2为其他机型就可以看

**Comment by isoulgh** [comment]
c口冷启动，睡眠后热拔插的问题没法解决嘛，我感觉就差这个问题黑苹果就完美了，哈哈

**Comment by CalvinXu17** [comment]
> c口冷启动，睡眠后热拔插的问题没法解决嘛，我感觉就差这个问题黑苹果就完美了，哈哈

感谢分享，我的C口只用来外接显示器，我这里外接显示器冷启动和热插拔是没有问题的

**Comment by isoulgh** [comment]
视频热拔插确实不管怎样都没问题。不过如果你用c口接u盘或者网线啥的，你就会发现开机必须插着u盘开机后才能热拔插，否则就只有电，但读不了u盘。而且插着开机之后正常用，但是睡眠之后u盘就又读不了了

**Comment by CalvinXu17** [comment]
IOElectrify驱动确实还存在这样的BUG，作者也已经很久未更新了，目前只能先这样用了😂

**Comment by isoulgh** [comment]
感谢感谢，感谢交流，我还想再问你一个关于三码的问题，
请问您知道该怎样获得一个属于自己的三码嘛，我使用tonyleelyy的引导里的三码没有问题，但是我去自己生成，只要更改了mlb和rom任意一个值，就无法登录imessage和facetime，相反，序列号和systemuuid我可以任意修改，不会出现无法登录iMessage和facetime的问题

**Comment by isoulgh** [comment]
我也按照官方文档的教程试了试，也还是不行，也有可能是我英语比较渣，漏了啥步骤的

**Comment by CalvinXu17** [comment]
AppleID退了然后在设备里删除后再用新的三码登陆试试，我这几天测机型换了好几个三码了也没出现啥问题🤣我是用Opencore Configurator自动生成的

**Comment by isoulgh** [comment]
我试过了不行诶，感觉我的电脑比较奇怪🤔，别人的电脑好像都是可以直接换😂，我电脑换了之后就是iMessage和facetime登录不了，其他倒是没啥问题
