### ISSUE TITLE
外接显示器分辨率不对

### ISSUE THREAD

**Issue by prozyy** [CalvinXu17/OpenCore-Dell-G3-3579-1060mq#2]
雷电3 外接LG UltraFine 4K 显示器，苹果系统显示器分辨率显示为 2560 x 1440

使用 https://github.com/CerteKim/Dell-G3-3579-3779-Hackintosh-OpenCore 这个EFI 显示器分辨率是正常的

**Comment by CalvinXu17** [comment]
> 雷电3 外接LG UltraFine 4K 显示器，苹果系统显示器分辨率显示为 2560 x 1440
> 
> 
> 
> 使用 https://github.com/CerteKim/Dell-G3-3579-3779-Hackintosh-OpenCore 这个EFI 显示器分辨率是正常的

手里没有4k屏，只能你自己再看看怎么搞了😔
